// ========================= Login - Constants
export const LOGIN_TO_PORTAL_SUCCESS = 'LOGIN_TO_PORTAL_SUCCESS';
export const LOGIN_TO_PORTAL_ERROR = 'LOGIN_TO_PORTAL_ERROR';
export const LOGOUT_FROM_PORTAL_SUCCESS = 'LOGOUT_FROM_PORTAL_SUCCESS';
export const LOGOUT_FROM_PORTAL_ERROR = 'LOGOUT_FROM_PORTAL_ERROR';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const AUTHENTICATION_EXPIRED = 'AUTHENTICATION_EXPIRED';
// ========================= Test Suite List - Constants
export const GET_ALL_TEST_SUITES_SUCCESS = 'GET_ALL_TEST_SUITES_SUCCESS';
export const GET_ALL_TEST_SUITES_ERROR = 'GET_ALL_TEST_SUITES_ERROR';

export const EXECUTE_TEST_BY_SUITE_ID_SUCCESS = 'EXECUTE_TEST_BY_SUITE_ID_SUCCESS';
export const EXECUTE_TEST_BY_SUITE_ID_ERROR = 'EXECUTE_TEST_BY_SUITE_ID_ERROR';

export const EXECUTE_TEST_BY_CASE_ID_SUCCESS = 'EXECUTE_TEST_BY_CASE_ID_SUCCESS';
export const EXECUTE_TEST_BY_CASE_ID_ERROR = 'EXECUTE_TEST_BY_CASE_ID_ERROR';

export const GET_ALL_CONNECTIONS_SUCCESS = 'GET_ALL_CONNECTIONS_SUCCESS';
export const GET_ALL_CONNECTIONS_ERROR = 'GET_ALL_CONNECTIONS_ERROR';
export const HIDE_MANAGE_CONNECTIONS_DIALOG = 'HIDE_MANAGE_CONNECTIONS_DIALOG';

export const SELECT_CONNECTIONS_SUCCESS = 'SELECT_CONNECTIONS_SUCCESS';
export const SELECT_CONNECTIONS_ERROR = 'SELECT_CONNECTIONS_ERROR';

export const GET_TESTCASE_LOG_BY_ID_SUCCESS = 'GET_TESTCASE_LOG_BY_ID_SUCCESS';
export const GET_TESTCASE_LOG_BY_ID_ERROR = 'GET_TESTCASE_LOG_BY_ID_ERROR';

export const MANAGE_CONNECTIONS_CASE_UPDATE = 'MANAGE_CONNECTIONS_CASE_UPDATE';

export const VIEW_TEST_CASE = 'VIEW_TEST_CASE';
export const HIDE_TEST_CASE_DIALOG = 'HIDE_TEST_CASE_DIALOG';
export const VIEW_TEST_CASE_LOG = 'VIEW_TEST_CASE_LOG';
export const HIDE_CASE_LOG_DIALOG = 'HIDE_CASE_LOG_DIALOG';

export const SHOW_TEST_CASE_EDIT_ENABLED = 'SHOW_TEST_CASE_EDIT_ENABLED';

export const SAVE_MANAGE_CONNECTION_DETAILS = 'SAVE_MANAGE_CONNECTION_DETAILS';
export const SHOW_TEST_CASE_VIEW_ENABLED = 'SHOW_TEST_CASE_VIEW_ENABLED';

// ========================= Test Suite Upload - Constants
export const TEST_SUITE_FILE_UPLOAD_SUCCESS = 'TEST_SUITE_FILE_UPLOAD_SUCCESS';
export const TEST_SUITE_SHEET_SELECT = 'TEST_SUITE_SHEET_SELECT';
export const TEST_SUITE_SHEET_LOAD_SUCCESS = 'TEST_SUITE_SHEET_LOAD_SUCCESS';
export const UPLOAD_TESTCASES_SUCCESS = 'UPLOAD_TESTCASES_SUCCESS';
export const TEST_CASE_SELECTION_CHANGE = 'TEST_CASE_SELECTION_CHANGE';
export const TEST_CASE_SELECT_ALL_TOGGLE = 'TEST_CASE_SELECT_ALL_TOGGLE';
export const RESET_TEST_SUITE_UPLOAD_DATA = 'RESET_TEST_SUITE_UPLOAD_DATA';

// ========================= Dashboard - Constants
export const GET_ORG_DATA_QUALITY_SUCCESS = 'GET_ORG_DATA_QUALITY_SUCCESS';
export const GET_ORG_DATA_QUALITY_ERROR = 'GET_ORG_DATA_QUALITY_ERROR';
export const GET_DQI_PROJECT_DETAILS_SUCCESS = 'GET_DQI_PROJECT_DETAILS_SUCCESS';

// ========================= DB Details - Constants
export const ADD_DB_DETAILS_SUCCESS = 'ADD_DB_DETAILS_SUCCESS';
export const ADD_DB_DETAILS_ERROR = 'ADD_DB_DETAILS_ERROR';

export const UPDATE_DB_DETAILS_SUCCESS = 'UPDATE_DB_DETAILS_SUCCESS';
export const UPDATE_DB_DETAILS_ERROR = 'UPDATE_DB_DETAILS_ERROR';

export const GET_ALL_DB_DETAILS_SUCCESS = 'GET_ALL_DB_DETAILS_SUCCESS';
export const GET_ALL_DB_DETAILS_ERROR = 'GET_ALL_DB_DETAILS_ERROR';

export const GET_DB_DETAILS_BY_ID_SUCCESS = 'GET_DB_DETAILS_BY_ID_SUCCESS';
export const GET_DB_DETAILS_BY_ID_ERROR = 'GET_DB_DETAILS_BY_ID_ERROR';