export const LOGIN_TO_PORTAL_SUCCESS = 'LOGIN_TO_PORTAL_SUCCESS';
export const LOGIN_TO_PORTAL_ERROR = 'LOGIN_TO_PORTAL_ERROR';

export const GET_ALL_TEST_SUITES_SUCCESS = 'GET_ALL_TEST_SUITES_SUCCESS';
export const GET_ALL_TEST_SUITES_ERROR = 'GET_ALL_TEST_SUITES_ERROR';

export const EXECUTE_TEST_BY_SUITE_ID_SUCCESS = 'EXECUTE_TEST_BY_SUITE_ID_SUCCESS';
export const EXECUTE_TEST_BY_SUITE_ID_ERROR = 'EXECUTE_TEST_BY_SUITE_ID_ERROR';

export const EXECUTE_TEST_BY_CASE_ID_SUCCESS = 'EXECUTE_TEST_BY_CASE_ID_SUCCESS';
export const EXECUTE_TEST_BY_CASE_ID_ERROR = 'EXECUTE_TEST_BY_CASE_ID_ERROR';

export const GET_ALL_CONNECTIONS_SUCCESS = 'GET_ALL_CONNECTIONS_SUCCESS';
export const GET_ALL_CONNECTIONS_ERROR = 'GET_ALL_CONNECTIONS_ERROR';

export const SELECT_CONNECTIONS_SUCCESS = 'SELECT_CONNECTIONS_SUCCESS';
export const SELECT_CONNECTIONS_ERROR = 'SELECT_CONNECTIONS_ERROR';

export const GET_ALL_DB_DETAILS_SUCCESS = 'GET_ALL_DB_DETAILS_SUCCESS';
export const GET_ALL_DB_DETAILS_ERROR = 'GET_ALL_DB_DETAILS_ERROR';

export const GET_DB_DETAILS_BY_ID_SUCCESS = 'GET_DB_DETAILS_BY_ID_SUCCESS';
export const GET_DB_DETAILS_BY_ID_ERROR = 'GET_DB_DETAILS_BY_ID_ERROR';

export const UPDATE_DB_DETAILS_SUCCESS = 'UPDATE_DB_DETAILS_SUCCESS';
export const UPDATE_DB_DETAILS_ERROR = 'UPDATE_DB_DETAILS_ERROR';

export const GET_TESTCASE_LOG_BY_ID_SUCCESS = 'GET_TESTCASE_LOG_BY_ID_SUCCESS';
export const GET_TESTCASE_LOG_BY_ID_ERROR = 'GET_TESTCASE_LOG_BY_ID_ERROR';

export const GET_ORG_DATA_QUALITY_SUCCESS = 'GET_ORG_DATA_QUALITY_SUCCESS';
export const GET_ORG_DATA_QUALITY_ERROR = 'GET_ORG_DATA_QUALITY_ERROR';

export const TEST_SUITE_FILE_UPLOAD_SUCCESS = 'TEST_SUITE_FILE_UPLOAD_SUCCESS';